name: afro_dip
description: A fly identification app powered by AI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  google_fonts: ^5.1.0
  shared_preferences: ^2.2.0
  image_picker: ^1.0.1
  path_provider: ^2.0.15
  sqflite: ^2.3.0
  path: ^1.8.3
  uuid: ^3.0.7
  intl: ^0.18.1
  lottie: ^2.5.0
  smooth_page_indicator: ^1.1.0
  share_plus: ^7.0.2
  connectivity_plus: ^4.0.1
  http: ^1.1.0
  
  # Firebase packages
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  
  # TensorFlow Lite
  tflite_flutter: ^0.10.1
  image: ^4.0.17
  
  # For camera preview
  camera: ^0.10.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/model/
    - assets/icons/
    - assets/images/

